import type { Locale, LocaleCopy } from '../i18n';

// Chrome copy for the CSV/Markdown/JSON/TXT/skill viewers. Values land in HTML and
// single-quoted JS strings: no quotes, backslashes or HTML specials.
const en = {
  backAllYours: 'Back to all your artifacts',
  allArtifacts: 'All artifacts',
  edit: 'Edit',
  stats: 'Stats',
  backAll: 'Back to all artifacts',
  favRemove: 'Remove from favorites',
  favAdd: 'Add to favorites',
  favorited: 'Favorited',
  favorite: 'Favorite',
  share: 'Share',
  download: 'Download',
  typeText: 'Text',
  typeImage: 'Image',
  typeVideo: 'Video',
  typeSkill: 'Skill',
  typeLibrary: 'Library',
  rows: 'rows',
  columns: 'columns',
  delimiter: 'Delimiter: ',
  comma: 'Comma',
  showingFirst: 'Showing first 1,000 of ',
  downloadAll: ' rows. Download the file to see all data.',
  filterRows: 'Filter rows...',
  of: ' of ',
  invalidJson: 'Invalid JSON content',
  expandAll: 'Expand All',
  collapseAll: 'Collapse All',
  copyPath: 'Copy Path',
  clickValue: 'Click a value to see its path',
  type: 'Type: ',
  items: 'items',
  keys: 'keys',
  contents: 'Contents',
  lines: 'lines',
  characters: 'characters',
  upvote: 'Upvote',
  savedToMine: 'Saved to My Skills',
  saveToMine: 'Save to My Skills',
  saved: 'Saved',
  save: 'Save',
  attachedTo: 'Attached to artifacts',
  usesByAgents: 'Uses by agents',
};

export type ViewerCopy = typeof en;

const es: ViewerCopy = {
  backAllYours: 'Volver a todas tus páginas',
  allArtifacts: 'Todas las páginas',
  edit: 'Editar',
  stats: 'Estadísticas',
  backAll: 'Volver a todas las páginas',
  favRemove: 'Quitar de favoritos',
  favAdd: 'Agregar a favoritos',
  favorited: 'En favoritos',
  favorite: 'Favorito',
  share: 'Compartir',
  download: 'Descargar',
  typeText: 'Texto',
  typeImage: 'Imagen',
  typeVideo: 'Video',
  typeSkill: 'Habilidad',
  typeLibrary: 'Biblioteca',
  rows: 'filas',
  columns: 'columnas',
  delimiter: 'Separador: ',
  comma: 'Coma',
  showingFirst: 'Mostrando las primeras 1.000 de ',
  downloadAll: ' filas. Descargá el archivo para ver todos los datos.',
  filterRows: 'Filtrar filas...',
  of: ' de ',
  invalidJson: 'El contenido no es un JSON válido',
  expandAll: 'Expandir todo',
  collapseAll: 'Contraer todo',
  copyPath: 'Copiar ruta',
  clickValue: 'Hacé clic en un valor para ver su ruta',
  type: 'Tipo: ',
  items: 'elementos',
  keys: 'claves',
  contents: 'Contenido',
  lines: 'líneas',
  characters: 'caracteres',
  upvote: 'Votar',
  savedToMine: 'Guardada en Mis habilidades',
  saveToMine: 'Guardar en Mis habilidades',
  saved: 'Guardada',
  save: 'Guardar',
  attachedTo: 'Sumada a páginas',
  usesByAgents: 'Usos de agentes',
};

export const VIEWER_COPY: LocaleCopy<ViewerCopy> = { en, es };

export function viewerCopy(locale: Locale | undefined): ViewerCopy {
  return VIEWER_COPY[locale ?? 'en'];
}
