// Generated by Wrangler by running `wrangler types`

interface Env {
	SLUGS: KVNamespace;
	RATE_LIMIT_KV: KVNamespace;
	PROXY_CACHE: KVNamespace;
	EMAIL_DEFAULT_FROM: "noreply@shareout.site";
	EMAIL_ARTIFACTS_DOMAIN: "shareout.site";
	SESSION_SECRET: string;
	SHAREOUT_BASE_URL: string;
	OPENAI_API_KEY: string;
	VERCEL_AI_GATEWAY: string;
	REALTIME: DurableObjectNamespace<import("./src/index").RealtimeCoordinator>;
	COMMENTS: DurableObjectNamespace<import("./src/index").CommentsCoordinator>;
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
}
