import type { LocaleCopy } from '../../../i18n';

// Viewer toolbar copy. Only the viewer's locale ships to the page. Values are
// trusted constants interpolated into HTML and single-quoted JS strings, so they
// must not contain quotes, backslashes or HTML specials (js() covers the English
// apostrophes).

const en = {
  openStudio: 'Open Live Studio',
  studioOff: 'Live Studio is not enabled for this workspace',
  editor: 'Editor',
  skillsTitle: 'Skills attached to this artifact',
  skills: 'Skills',
  attachedSkills: 'Attached skills',
  close: 'Close',
  skillsIntro: 'Knowledge attached to this artifact — agents working on it read these as context.',
  backAll: 'Back to all artifacts',
  allArtifacts: 'All artifacts',
  backAllYours: 'Back to all your artifacts',
  favRemove: 'Remove from favorites',
  favAdd: 'Add to favorites',
  favorited: 'Favorited',
  favorite: 'Favorite',
  shareTitle: 'Share this page',
  share: 'Share',
  liveViewers: 'Live viewers',
  viewingNow: 'viewing now',
  youInitial: 'Y',
  notifyTitle: 'Get this page sent to you on a schedule (email, Telegram, or Slack)',
  notifyMe: 'Notify me',
  followTitle: 'Get alerted when a metric on this page crosses a threshold',
  followMetric: 'Follow metric',
  comments: 'Comments',
  loginToComment: 'Log in to comment',
  stats: 'Stats',
  settings: 'Settings',
  scheduleTitle: 'Schedule delivery (email, Telegram, or Slack)',
  schedule: 'Schedule',
  toggleToolbar: 'Toggle toolbar',
  analytics: 'Analytics',
  loadingStats: 'Loading stats...',
  fullDashboard: 'View full dashboard →',
  loadingDots: 'Loading...',
  closeComments: 'Close comments',
  open: 'Open',
  resolved: 'Resolved',
  loadingComments: 'Loading comments…',
  nameRequired: 'Your name (required)',
  nameOptional: 'Your name (optional)',
  yourName: 'Your name',
  addComment: 'Add a comment…',
  useMention: ' use @ to mention',
  addCommentAria: 'Add a comment',
  pinTitle: 'Attach this comment to a spot on the page',
  pinToPage: 'Pin to page',
  comment: 'Comment',
  // script-core
  justNow: 'just now',
  dragToMove: 'Drag to move',
  // script-auth
  cronDaily: 'Daily 9:00 UTC',
  cronWeekdays: 'Weekdays 9:00 UTC',
  cronWeekly: 'Weekly Mon 9:00 UTC',
  cronHourly: 'Hourly',
  whereGo: 'Where should it go?',
  deliveryDest: 'Delivery destination',
  myTelegram: 'My Telegram',
  linkedChat: 'Your linked chat',
  wsConnection: 'Workspace connection',
  email: 'Email',
  yourInbox: 'Your inbox',
  oneOrMore: 'One or more addresses',
  slackTarget: 'Slack target',
  channel: 'Channel',
  dm: 'Direct message',
  slackConn: 'Slack connection',
  egTeam: 'e.g. team',
  connHint: 'The name from your workspace connections',
  channelId: 'Channel ID',
  slackMemberId: 'Your Slack member ID',
  sendTo: 'Send to',
  deliveredToAccount: 'Delivered to the email on your ShareOut account',
  recipients: 'Recipients',
  recipientsPh: 'you@company.com, team@company.com',
  commaSep: 'Comma-separated, up to 10 addresses',
  scheduleDelivery: 'Schedule delivery',
  notifyLead: 'Get this artifact sent to you on a recurring schedule.',
  scheduleLead: 'Deliver this artifact by email, Slack, or Telegram on a schedule.',
  deliveryDetails: 'Delivery details',
  whatToSend: 'What to send',
  modeMessage: 'Message + link',
  modeSnapshot: 'Image snapshot',
  modeBoth: 'Message + snapshot',
  howOften: 'How often',
  cancel: 'Cancel',
  startNotifs: 'Start notifications',
  createSchedule: 'Create schedule',
  accountEmail: 'Your account email',
  errOneEmail: 'Enter at least one email address.',
  errNoEmail: 'Your account has no email on file.',
  errSlackConn: 'Enter the Slack connection name.',
  errSlackMember: 'Enter your Slack member ID.',
  errChannel: 'Enter the channel ID.',
  errSchedule: 'Failed to create schedule.',
  errNetwork: 'Network error.',
  followModalTitle: 'Follow a metric',
  followLead: 'Get notified when a number crosses a threshold you care about.',
  whatToWatch: 'What to watch',
  metric: 'Metric',
  loading: 'Loading…',
  alertWhen: 'Alert when it',
  dropsBelow: 'Drops below',
  risesAbove: 'Rises above',
  threshold: 'Threshold',
  whereNotify: 'Where to notify you',
  alertDest: 'Alert destination',
  slackDm: 'Slack DM',
  howOftenCheck: 'How often to check',
  crewCheck: 'Also have the crew investigate when it fires',
  createAlert: 'Create alert',
  noMetrics: 'No followable metrics',
  failedLoad: 'Failed to load',
  activeAlerts: 'Your active alerts',
  paused: '(paused)',
  errPickMetric: 'Pick a metric first.',
  errThreshold: 'Enter a threshold value.',
  errAlert: 'Failed to create alert.',
  alertCreated: 'Alert created.',
  followPrefix: 'Follow ',
  // script-comments
  you: 'You',
  loadFail: "Couldn't load comments. Try again?",
  due: 'Due ',
  agent: '🤖 Agent',
  resolvedSuffix: ' · resolved',
  reply: 'Reply',
  reopen: 'Reopen',
  resolve: 'Resolve',
  assign: 'Assign',
  replies: 'Replies',
  addReaction: 'Add reaction',
  loginReact: 'Please log in to react.',
  noResolved: 'No resolved comments yet.',
  noComments: 'No comments yet. Start the conversation!',
  noReplies: 'No replies yet',
  repliesFail: "Couldn't load replies",
  replyingTo: 'Replying to ',
  unassign: '✕ Unassign',
  dueDate: 'Due date ',
  setDue: 'Set due',
  loginAssign: 'Please log in to assign.',
  enterName: 'Please enter your name to comment.',
  anonymous: 'Anonymous',
  posted: 'Comment posted.',
  loginComment: 'Please log in to comment.',
  postFail: "Couldn't post comment. Try again?",
  clickPage: 'Click the page…',
  pinned: 'Pinned ✓',
  oneOther: '1 other here',
  othersHere: ' others here',
  isTyping: ' is typing…',
  connecting: 'Connecting…',
  reconnecting: 'Reconnecting…',
  connLost: 'Connection lost. Reopen comments to retry.',
};

export type ToolbarCopy = typeof en;

const es: ToolbarCopy = {
  openStudio: 'Abrir el editor en vivo',
  studioOff: 'El editor en vivo no está activado en este espacio',
  editor: 'Editar',
  skillsTitle: 'Habilidades sumadas a esta página',
  skills: 'Habilidades',
  attachedSkills: 'Habilidades sumadas',
  close: 'Cerrar',
  skillsIntro: 'Conocimiento sumado a esta página: los agentes que trabajan en ella lo leen como contexto.',
  backAll: 'Volver a todas las páginas',
  allArtifacts: 'Todas las páginas',
  backAllYours: 'Volver a todas tus páginas',
  favRemove: 'Quitar de favoritos',
  favAdd: 'Agregar a favoritos',
  favorited: 'En favoritos',
  favorite: 'Favorito',
  shareTitle: 'Compartir esta página',
  share: 'Compartir',
  liveViewers: 'Quiénes la están viendo',
  viewingNow: 'viendo ahora',
  youInitial: 'V',
  notifyTitle: 'Recibí esta página cada cierto tiempo (mail, Telegram o Slack)',
  notifyMe: 'Avisarme',
  followTitle: 'Recibí un aviso cuando un número de esta página pase un límite',
  followMetric: 'Seguir un número',
  comments: 'Comentarios',
  loginToComment: 'Entrá para comentar',
  stats: 'Estadísticas',
  settings: 'Configuración',
  scheduleTitle: 'Programar envíos (mail, Telegram o Slack)',
  schedule: 'Programar',
  toggleToolbar: 'Mostrar u ocultar la barra',
  analytics: 'Estadísticas',
  loadingStats: 'Cargando estadísticas...',
  fullDashboard: 'Ver el panel completo →',
  loadingDots: 'Cargando...',
  closeComments: 'Cerrar comentarios',
  open: 'Abiertos',
  resolved: 'Resueltos',
  loadingComments: 'Cargando comentarios…',
  nameRequired: 'Tu nombre (obligatorio)',
  nameOptional: 'Tu nombre (opcional)',
  yourName: 'Tu nombre',
  addComment: 'Escribí un comentario…',
  useMention: ' usá @ para mencionar',
  addCommentAria: 'Escribí un comentario',
  pinTitle: 'Fijá este comentario en un lugar de la página',
  pinToPage: 'Fijar en la página',
  comment: 'Comentar',
  justNow: 'recién',
  dragToMove: 'Arrastrá para mover',
  cronDaily: 'Todos los días 9:00 UTC',
  cronWeekdays: 'De lunes a viernes 9:00 UTC',
  cronWeekly: 'Los lunes 9:00 UTC',
  cronHourly: 'Cada hora',
  whereGo: '¿A dónde la mandamos?',
  deliveryDest: 'Destino del envío',
  myTelegram: 'Mi Telegram',
  linkedChat: 'Tu chat vinculado',
  wsConnection: 'Conexión del espacio',
  email: 'Mail',
  yourInbox: 'Tu bandeja de entrada',
  oneOrMore: 'Una o más direcciones',
  slackTarget: 'Destino en Slack',
  channel: 'Canal',
  dm: 'Mensaje directo',
  slackConn: 'Conexión de Slack',
  egTeam: 'por ejemplo, equipo',
  connHint: 'El nombre que tiene en las conexiones de tu espacio',
  channelId: 'ID del canal',
  slackMemberId: 'Tu ID de miembro en Slack',
  sendTo: 'Enviar a',
  deliveredToAccount: 'Llega al mail de tu cuenta de ShareOut',
  recipients: 'Destinatarios',
  recipientsPh: 'vos@empresa.com, equipo@empresa.com',
  commaSep: 'Separadas por comas, hasta 10 direcciones',
  scheduleDelivery: 'Programar envíos',
  notifyLead: 'Recibí esta página cada cierto tiempo.',
  scheduleLead: 'Mandá esta página por mail, Slack o Telegram cada cierto tiempo.',
  deliveryDetails: 'Detalles del envío',
  whatToSend: 'Qué mandar',
  modeMessage: 'Mensaje + enlace',
  modeSnapshot: 'Captura de imagen',
  modeBoth: 'Mensaje + captura',
  howOften: 'Cada cuánto',
  cancel: 'Cancelar',
  startNotifs: 'Activar avisos',
  createSchedule: 'Programar envío',
  accountEmail: 'El mail de tu cuenta',
  errOneEmail: 'Escribí al menos una dirección de mail.',
  errNoEmail: 'Tu cuenta no tiene un mail cargado.',
  errSlackConn: 'Escribí el nombre de la conexión de Slack.',
  errSlackMember: 'Escribí tu ID de miembro en Slack.',
  errChannel: 'Escribí el ID del canal.',
  errSchedule: 'No pudimos programar el envío. Probá de nuevo.',
  errNetwork: 'Error de conexión.',
  followModalTitle: 'Seguir un número',
  followLead: 'Te avisamos cuando un número que te importa pase un límite.',
  whatToWatch: 'Qué mirar',
  metric: 'Número',
  loading: 'Cargando…',
  alertWhen: 'Avisarme cuando',
  dropsBelow: 'Baje de',
  risesAbove: 'Supere',
  threshold: 'Límite',
  whereNotify: 'Dónde avisarte',
  alertDest: 'Destino del aviso',
  slackDm: 'Mensaje directo en Slack',
  howOftenCheck: 'Cada cuánto revisar',
  crewCheck: 'Que los agentes investiguen cuando salte el aviso',
  createAlert: 'Crear aviso',
  noMetrics: 'No hay números para seguir',
  failedLoad: 'No se pudo cargar',
  activeAlerts: 'Tus avisos activos',
  paused: '(en pausa)',
  errPickMetric: 'Elegí un número primero.',
  errThreshold: 'Escribí un valor límite.',
  errAlert: 'No pudimos crear el aviso. Probá de nuevo.',
  alertCreated: 'Aviso creado.',
  followPrefix: 'Seguir ',
  you: 'Vos',
  loadFail: 'No pudimos cargar los comentarios. ¿Probás de nuevo?',
  due: 'Vence el ',
  agent: '🤖 Agente',
  resolvedSuffix: ' · resuelto',
  reply: 'Responder',
  reopen: 'Reabrir',
  resolve: 'Resolver',
  assign: 'Asignar',
  replies: 'Respuestas',
  addReaction: 'Reaccionar',
  loginReact: 'Entrá para reaccionar.',
  noResolved: 'Todavía no hay comentarios resueltos.',
  noComments: 'Todavía no hay comentarios. Arrancá la conversación.',
  noReplies: 'Todavía no hay respuestas',
  repliesFail: 'No pudimos cargar las respuestas',
  replyingTo: 'Respondiendo a ',
  unassign: '✕ Quitar asignación',
  dueDate: 'Vence ',
  setDue: 'Poner fecha',
  loginAssign: 'Entrá para asignar.',
  enterName: 'Escribí tu nombre para comentar.',
  anonymous: 'Anónimo',
  posted: 'Comentario publicado.',
  loginComment: 'Entrá para comentar.',
  postFail: 'No pudimos publicar el comentario. ¿Probás de nuevo?',
  clickPage: 'Hacé clic en la página…',
  pinned: 'Fijado ✓',
  oneOther: '1 persona más acá',
  othersHere: ' personas más acá',
  isTyping: ' está escribiendo…',
  connecting: 'Conectando…',
  reconnecting: 'Reconectando…',
  connLost: 'Se perdió la conexión. Volvé a abrir los comentarios para reintentar.',
};

export const TOOLBAR_COPY: LocaleCopy<ToolbarCopy> = { en, es };

/** Escape a copy string for a single-quoted JS string inside the inline script. */
export function js(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
